### ISSUE TITLE
Problem with `socketConnection`

### ISSUE THREAD

**Issue by BarkingBad** [mikiisz/mikiisz.github.io#1]
Sending undefined object with `socketConnection.send()` via developer console causes crash.

**Comment by KacperFKorban** [comment]
Pls fix that

**Comment by KacperFKorban** [comment]
This is a blocker :disappointed:

**Comment by KacperFKorban** [comment]
I'm starting to think that this issue isn't going to be fixed :disappointed:

**Comment by mikiisz** [comment]
This project is currently not on our roadmap

**Comment by mikiisz** [comment]
Im closing due to long period of inactivity

**Comment by BarkingBad** [comment]
Great project with potential killed by moody dev 🙄


sad

**Comment by mikiisz** [comment]
Let me see what I can do

**Comment by KacperFKorban** [comment]
I'm starting to lose patience. Plus some new issues occured ![Screenshot_20200925-215603~2.png](https://user-images.githubusercontent.com/39772805/94310973-c5550d80-ff7a-11ea-94d2-83e45a145f09.png)

**Comment by mikiisz** [comment]
The next release is planned for tomorrow evening. My teams is going to have a live hackathon between 6PM - 8PM Poland time

**Comment by mikiisz** [comment]
the fix will be released tomorrow, im closing the issue

**Comment by KacperFKorban** [comment]
> The next release is planned for tomorrow evening. My teams is going to have a live hackathon between 6PM - 8PM Poland time

Is it already UTC+01:00 or still UTC+02:00?

**Comment by mikiisz** [comment]
it will be UTC+02:00

**Comment by BarkingBad** [comment]
@mikiisz , you are the best developer i have ever seen. You are so passionate with your work. I strongly believe the product you are developing can make a difference in this 'remote working' word. Keep up your fantastic work 👍 ❤️

**Comment by mikiisz** [comment]
im sorry to hear that. We are doing everything that is possible to address the issue

**Comment by mikiisz** [comment]
I can see that community of WebRTC is more toxic then i expected
