### ISSUE TITLE
Service constantly down

### ISSUE THREAD

**Issue by KacperFKorban** [mikiisz/mikiisz.github.io#2]
Service is constantly down. It is really annoying since this is a blocker from my whole team/project. Please fix it ASAP

**Comment by BarkingBad** [comment]
Yes, this is really annoying. At my company, we had scheduled online meeting today. We planned to use this lightweight and modern conference system which was said to be ready to use. However, it was down, so we had to change it to Cisco Webex. I hope you could deliver more stable solution.

**Comment by KacperFKorban** [comment]
Attached to this comment, You can find a screenshot that will possibly aid You in debugging this problem. 
![image](https://user-images.githubusercontent.com/39772805/97785439-44a2b600-1ba5-11eb-8488-45c939d4405b.png)

**Comment by mikiisz** [comment]
Will fix

**Comment by KacperFKorban** [comment]
I feel like I'm not being taken seriously here. The UX is really bad and the frontend is non-existent.

**Comment by BarkingBad** [comment]
Sad

**Comment by mikiisz** [comment]
Im reporting you guys at this moment
